Aws-ha test case
ksctl/ksctl pull request #382
Opened 2024-06-07 06:01 UTC by Horiodino

# Tasks description

### Related Issue(s)
- https://github.com/ksctl/ksctl/issues/324

# Note to reviewers

- :heavy_check_mark: Ran Tests locally
- :heavy_check_mark: Checked [Contribution's guidelines](https://docs.ksctl.com/docs/contribution-guidelines/)

2024-06-07 18:27 UTC, dipankardas011 commented on internal/cloudproviders/aws/network.go
> +		mainStateDocument.CloudInfra.Aws.GatewayID = *gatewayresp.InternetGateway.InternetGatewayId
Make sure these assigned empty_str during deletion

2024-06-07 18:39 UTC, dipankardas011 commented
@Horiodino can you check why is this stuck?

![image](https://github.com/ksctl/ksctl/assets/65275144/74ee7de4-4a16-4bec-83e5-88145364e646)

2024-06-07 18:42 UTC, dipankardas011 commented on internal/cloudproviders/aws/aws_test.go
> -	assert.DeepEqual(t, expectEgr.IpPermissions[0].IpRanges[0].Description, gotEgr.IpPermissions[0].IpRanges[0].Description)
Not sure why is this removed?

2024-06-07 18:42 UTC, dipankardas011 requested changes
Changes needed

2024-06-08 05:08 UTC, dipankardas011 commented
@Horiodino I have changed the base of the test suite to the pr branch of error handling so that we can merge this to that and make aws changes once this is merged to that PR

2024-06-08 05:09 UTC, dipankardas011 commented on internal/cloudproviders/aws/aws_test.go
> -	assert.DeepEqual(t, expectEgr.IpPermissions[0].IpRanges[0].Description, gotEgr.IpPermissions[0].IpRanges[0].Description)
also check what all where already there and keep those unit test cases

2024-06-08 07:32 UTC, Horiodino commented on internal/cloudproviders/aws/awsgo.go
> +					Value: aws.String(*parameter.TagSpecifications[0].Tags[0].Value),
na because the method itself needs pointer

2024-06-08 17:44 UTC, dipankardas011 commented
@Horiodino have you rebeased it?

2024-06-09 03:25 UTC, merged